In [3]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.request import urlretrieve
import time

url = 'http://movie.naver.com/movie/sdb/rank/rmovie.nhn'
get_url = 'http://movie.naver.com'

page = urlopen(url)
soup = BeautifulSoup(page,"html.parser")
tit3 = soup.find_all("div",attrs={"class":"tit3"})

li = []
for i in range(5):
    li.append( url + tit3[i].find('a')['href'])


li_p = []
k = 0
for i in li:
    k+=1
    page = urlopen(i)
    soup = BeautifulSoup(page,"html.parser")
    img = soup.find("div",attrs={"class":"poster"}).find("img")["src"]
    urlretrieve(img,  "1.jpg")
    time.sleep(2)



In [76]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

t = 1.53
df = 5

prop = stats.t.cdf(t,df)
print("P(T<={0}) : {1:.3f}".format(t,porp))

AttributeError: module 'statsmodels.api' has no attribute 't'

In [78]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.request import urlretrieve
import pandas as pd
import json
import sqlite3
import requests

url = "http://www.nlotto.co.kr/common.do?method=getLottoNumber&drwNo=1"
page = urlopen(url)
data = json.loads(page.read())
print(data)

CertificateError: hostname 'www.nlotto.co.kr' doesn't match either of '*.dhlottery.co.kr', 'dhlottery.co.kr'

In [100]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

mu = 2
prop = stats.poisson.pmf(2,2)
cdf_prop = stats.poisson.cdf(1,2)
cdf_prop1 = stats.poisson.cdf(2,2)
print("1분당 {0}번의 전화가 걸려올 확률: {1:.4f}".format(2,prop))
print("1분당 {0}회의 전화가 걸려올 확률: {1:.4f}".format(2,cdf_prop))
print("1분당 {0}회의 전화가 걸려올 확률: {1:.4f}".format(2,1-cdf_prop1))

1분당 2번의 전화가 걸려올 확률: 0.2707
1분당 2회의 전화가 걸려올 확률: 0.4060
1분당 2회의 전화가 걸려올 확률: 0.3233


In [121]:
ds_mycars = pd.read_csv(".\mycars.csv",engine="python")
df=ds_mycars[['model','mpg']]
df.groupby('model').describe()


mpg                                                 \
                       count       mean       std   min    25%   50%    75%   
model                                                                         
4runner 4wd              6.0  15.166667  0.752773  14.0  15.00  15.0  15.75   
a4                       7.0  18.857143  1.864454  16.0  18.00  18.0  20.50   
a4 quattro               8.0  17.125000  1.807722  15.0  15.75  17.0  18.25   
a6 quattro               3.0  16.000000  1.000000  15.0  15.50  16.0  16.50   
altima                   6.0  20.666667  1.966384  19.0  19.00  20.0  22.50   
c1500 suburban 2wd       5.0  12.800000  1.303840  11.0  12.00  13.0  14.00   
camry                    7.0  19.857143  1.463850  18.0  18.50  21.0  21.00   
camry solara             7.0  19.857143  1.772811  18.0  18.00  21.0  21.00   
caravan 2wd             11.0  15.818182  1.834022  11.0  15.50  16.0  17.00   
civic                    9.0  24.444444  1.943651  21.0  24.00  24.0  25.00   
corolla                  5.0  25.600000  1.673320  24.0  24.00  26.0  26.00   
corvette                 5.0  15.400000  0.547723  15.0  15.00  15.0  16.00   
dakota pickup 4wd        9.0  12.777778  1.986063   9.0  11.00  14.0  14.00   
durango 4wd              7.0  11.857143  1.573592   9.0  11.00  13.0  13.00   
expedition 2wd           3.0  11.333333  0.577350  11.0  11.00  11.0  11.50   
explorer 4wd             6.0  13.666667  0.816497  13.0  13.00  13.5  14.00   
f150 pickup 4wd          7.0  13.000000  1.000000  11.0  13.00  13.0  13.50   
forester awd             6.0  18.833333  0.983192  18.0  18.00  18.5  19.75   
grand cherokee 4wd       8.0  13.500000  2.507133   9.0  12.50  14.0  15.00   
grand prix               5.0  17.000000  1.000000  16.0  16.00  17.0  18.00   
gti                      5.0  20.000000  2.000000  17.0  19.00  21.0  21.00   
impreza awd              8.0  19.625000  0.744024  19.0  19.00  19.5  20.00   
jetta                    9.0  21.222222  4.867694  16.0  19.00  21.0  21.00   
k1500 tahoe 4wd          4.0  12.500000  1.732051  11.0  11.00  12.5  14.00   
land cruiser wagon 4wd   2.0  12.000000  1.414214  11.0  11.50  12.0  12.50   
malibu                   5.0  18.800000  1.923538  17.0  18.00  18.0  19.00   
maxima                   3.0  18.666667  0.577350  18.0  18.50  19.0  19.00   
mountaineer 4wd          4.0  13.250000  0.500000  13.0  13.00  13.0  13.25   
mustang                  9.0  15.888889  1.452966  14.0  15.00  15.0  17.00   
navigator 2wd            3.0  11.333333  0.577350  11.0  11.00  11.0  11.50   
new beetle               6.0  24.000000  6.511528  19.0  20.00  20.5  27.00   
passat                   7.0  18.571429  1.902379  16.0  17.50  18.0  20.00   
pathfinder 4wd           4.0  13.750000  1.258306  12.0  13.50  14.0  14.25   
ram 1500 pickup 4wd     10.0  11.400000  1.505545   9.0  11.00  11.5  12.75   
range rover              4.0  11.500000  0.577350  11.0  11.00  11.5  12.00   
sonata                   7.0  19.000000  1.414214  18.0  18.00  18.0  20.00   
tiburon                  7.0  18.285714  1.603567  16.0  17.00  19.0  19.50   
toyota tacoma 4wd        7.0  15.571429  0.786796  15.0  15.00  15.0  16.00   

                              
                         max  
model                         
4runner 4wd             16.0  
a4                      21.0  
a4 quattro              20.0  
a6 quattro              17.0  
altima                  23.0  
c1500 suburban 2wd      14.0  
camry                   21.0  
camry solara            22.0  
caravan 2wd             18.0  
civic                   28.0  
corolla                 28.0  
corvette                16.0  
dakota pickup 4wd       15.0  
durango 4wd             13.0  
expedition 2wd          12.0  
explorer 4wd            15.0  
f150 pickup 4wd         14.0  
forester awd            20.0  
grand cherokee 4wd      17.0  
grand prix              18.0  
gti                     22.0  
impreza awd             21.0  
jetta     

In [128]:
ds_mycars = pd.read_csv(".\Exh_QC1.csv",engine="python")
df=ds_mycars[['Flaws','Period']]
count = df['Flaws'].value_counts().sort_index()
cumcnt=np.cumsum(count)
percent=count/sum(count)*100
cumpct=np.cumsum(percent)
count_data=pd.DataFrame({'Count':count,'cumCnt':cumcnt,'Percent':percent,'CumPct':cumpct})
count_data.columns.name='Flaws'
count_data


Flaws    Count  cumCnt  Percent  CumPct
Other        6       6     15.0    15.0
Peel        15      21     37.5    52.5
Scratch     13      34     32.5    85.0
Smudge       6      40     15.0   100.0

In [133]:
ds_example = pd.read_csv(".\EXH_QC.csv",engine="python")
df =ds_example[['Cabbage weight']].copy()

lower,upper=stats.norm.interval(0.95,loc=2.7,scale=0.397/np.sqrt(40))
print("신뢰구간: ({0},{1})" .format(lower.round(2),upper.round(2)))
lower,upper=stats.norm.interval(0.95,loc=df.mean() ,scale=stats.sem(df))
print("신뢰구간: ({0},{1})" .format(lower.round(2),upper.round(2)))

신뢰구간: (2.58,2.82)
신뢰구간: ([2.57],[2.82])


In [134]:
df=pd.DataFrame({'sample':[54.1,53.3,56.1,54.0,54.1,54.5,57.1,55.2,53.8,54.1,54.1,56.1,55.0,55.9,56.0,54.9,54.3,53.9,55.0]})
lower,upper=stats.t.interval(0.95,len(df)-1,loc=np.mean(df),scale=stats.sem(df))
print("신뢰구간: ({0},{1})" .format(lower.round(2),upper.round(2)))

신뢰구간: ([54.33],[55.31])


In [135]:
df=pd.DataFrame({'sample':[73,71,74,69,70,73,70,68,75,72,70,72,73,70,70,72,71,70,75,72]})
lower,upper=stats.t.interval(0.95,len(df)-1,loc=np.mean(df),scale=stats.sem(df))
print("신뢰구간: ({0},{1})" .format(lower.round(2),upper.round(2)))

신뢰구간: ([70.6],[72.4])


In [138]:
df=pd.DataFrame({'sample':[74.5,81,2,93.8,82.0,76.3,75.7,80.2,72.6,77.9,82.8]})
t_result = stats.ttest_1samp(df,76.7)
t,p=t_result.statistic.round(3),t_result.pvalue.round(3)
print("1-Sample t-test")
print("t검정 통계량 : {}".format(t))
print("p-value : P{}".format(p))

1-Sample t-test
t검정 통ㄹ계량 : [-0.562]
p-value : P[0.587]


In [15]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest
import scipy.stats

df = pd.DataFrame({'sample': [85.0,79.0,79.1,79.9,81.6,78.6,85.4,83.4,78.1,79.2]})

t_result = stats.ttest_1samp(df,76.7)

t,p = t_result.statistic.round(3),t_result.pvalue.round(3)

print("t검정통계량 : {} ".format(t))
print("p-value : {}".format(p))

t검정통계량 : [4.879] 
p-value : [0.001]


In [17]:
import numpy as np
import scipy.stats
from scipy import stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

df1 = pd.DataFrame({'before': [720,589,780,648,720,589,780,648,780,648]})
df2 = pd.DataFrame({'after': [810,670,790,712,810,670,790,712,790,712]})

t_result = stats.ttest_rel(df1,df2)
t,p=t_result.statistic.round(3),t_result.pvalue.round(3)
print("t검정통계량 : {}" .format(t))
print("p value : {}" .format(p))

t검정통계량 : [-5.324]
p value : [0.]


In [3]:
df1 = pd.DataFrame({'before': [720,589,780,648,720,589,780,648,780,648]})
df2 = pd.DataFrame({'after': [710,580,787,712,750,600,782,670,790,680]})

t_result = stats.ttest_rel(df1,df2)
t,p=t_result.statistic.round(3),t_result.pvalue.round(3)
print("t검정통계량 : {}" .format(t))
print("p value : {}" .format(p))

t검정통계량 : [-2.266]
p value : [0.05]


In [5]:
df1 = pd.DataFrame({'A': [892,623,721,678,723,790,720,670,690,771]})
df2 = pd.DataFrame({'B': [721,821,910,678,723,790,711,790,745,891]})
df3 = pd.DataFrame({'C': [621,915,888,721,894,834,841,912,845,889]})

t_result = stats.f_oneway(df1,df2,df3)
t,p=t_result.statistic.round(3),t_result.pvalue.round(3)
print("t검정통계량 : {}" .format(t))
print("p value : {}" .format(p))

t검정통계량 : [4.263]
p value : [0.025]


In [7]:
count =15
nobs = 100
value =.1

stat,pval=proportions_ztest(count,nobs,value)
print('{0:0.3f}'.format(stat))
print('{0:0.3f}'.format(pval))

1.400
0.161


In [9]:
count = np.array([14,5])
nobs = np.array([1200,1200])

stat,pval=proportions_ztest(count,nobs)
print('{0:0.3f}'.format(stat))
print('{0:0.3f}'.format(pval))

2.073
0.038


In [24]:
import numpy as np
from scipy import stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest
import scipy.stats

df = pd.DataFrame({'HSG':[270,260,236,234],'SS':[228,285,225,262],'SPA':[277,284,231,208]})
chi , pval, dof,expected = stats.chi2_contingency(df.T)
print('{0:0.3f}'.format(chi))
print('{0:0.3f}'.format(pval))
print('{0:0.3f}'.format(dof))
print('{}'.format(expected.round(3)))

13.366
0.038
6.000
[[258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]]


In [25]:
df1 = [1,2,3,4,4,5,6,6,7,8]
df2 = [23,29,49,64,74,87,96,97,109,119]

corr , pval = stats.pearsonr(df1,df2)
print('{0:0.3f}'.format(corr))
print('{0:0.3f}'.format(pval))

0.989
0.000


In [26]:
MOD = 20000303
print(int(input())%MOD)

20000303200003032000030320000303200003032000030320000303200003032000030320000303
0


In [ ]:
df1 = [37.6,38.6,37.2,36.4,38.6,39,37.2,36.1,35.9,,37.1,36.9,37.5,36..]
df2 = [23,29,49,64,74,87,96,97,109,119]

corr , pval = stats.pearsonr(df1,df2)
print('{0:0.3f}'.format(corr))
print('{0:0.3f}'.format(pval))

In [29]:
MINUTES =[37.6,38.6,37.2,36.4,38.6,39]
UNITS=[23,29,49,64,74,87,96,97,109,119]
MINUTES = sm.add_constant(MINUTES)
model = sm.OLS(UNITS,MINUTES)
result = model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     365.3
Date:                Fri, 25 Jan 2019   Prob (F-statistic):           5.82e-08
Time:                        11:27:29   Log-Likelihood:                -29.401
No. Observations:                  10   AIC:                             62.80
Df Residuals:                       8   BIC:                             63.41
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1712      3.886      1.845      0.1

C:\Users\admin1\Anaconda3\lib\site-packages\scipy\stats\stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


In [ ]:
MINUTES =[37.6,38.6,37.2,36.4,38.6,39,37.2,36.1,35.9,37.1]
UNITS=[23,29,49,64,74,87,96,97,109,119]
MINUTES = sm.add_constant(MINUTES)
model = sm.OLS(UNITS,MINUTES)
result = model.fit()
print(result.summary())