In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',',dtype=np.float32)
x_data = xy[:, 0:-1] # 0 to the (last element -1)
y_data = xy[:, [-1]] # y data is only one so [-1]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3]) # number of x's data is 3
Y = tf.placeholder(tf.float32, shape=[None, 1]) # number of y's data is 1

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost / Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the Loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110],[90, 100, 80]]}))


0 Cost:  16253.933 
Prediction:
 [[36.568943]
 [49.731712]
 [45.79667 ]
 [51.63565 ]
 [38.095108]]
10 Cost:  1.7920351 
Prediction:
 [[149.34665]
 [185.2768 ]
 [179.35434]
 [197.07578]
 [141.48123]]
20 Cost:  1.6403275 
Prediction:
 [[149.69069]
 [185.685  ]
 [179.75937]
 [197.51602]
 [141.79198]]
30 Cost:  1.6373923 
Prediction:
 [[149.69455]
 [185.68436]
 [179.76152]
 [197.51753]
 [141.79086]]
40 Cost:  1.6344748 
Prediction:
 [[149.69737]
 [185.68248]
 [179.76244]
 [197.51772]
 [141.7888 ]]
50 Cost:  1.6315765 
Prediction:
 [[149.70018]
 [185.6806 ]
 [179.76337]
 [197.5179 ]
 [141.78674]]
60 Cost:  1.6286867 
Prediction:
 [[149.70297]
 [185.67871]
 [179.76428]
 [197.51807]
 [141.78468]]
70 Cost:  1.6258166 
Prediction:
 [[149.70578]
 [185.67686]
 [179.76521]
 [197.51826]
 [141.78265]]
80 Cost:  1.6229322 
Prediction:
 [[149.70857]
 [185.67499]
 [179.76613]
 [197.51842]
 [141.78062]]
90 Cost:  1.6200926 
Prediction:
 [[149.71135]
 [185.67313]
 [179.76703]
 [197.5186 ]
 [141.7786 ]]
1

1180 Cost:  1.3738673 
Prediction:
 [[149.97664]
 [185.49658]
 [179.85507]
 [197.52989]
 [141.59113]]
1190 Cost:  1.3720988 
Prediction:
 [[149.97874]
 [185.49516]
 [179.85576]
 [197.52992]
 [141.58968]]
1200 Cost:  1.3703207 
Prediction:
 [[149.98087]
 [185.49376]
 [179.85648]
 [197.52995]
 [141.58824]]
1210 Cost:  1.3685689 
Prediction:
 [[149.98297]
 [185.49237]
 [179.85718]
 [197.53   ]
 [141.58682]]
1220 Cost:  1.3668189 
Prediction:
 [[149.98509]
 [185.491  ]
 [179.85791]
 [197.53006]
 [141.5854 ]]
1230 Cost:  1.3650777 
Prediction:
 [[149.98717]
 [185.48958]
 [179.8586 ]
 [197.53008]
 [141.58397]]
1240 Cost:  1.3633276 
Prediction:
 [[149.98927]
 [185.4882 ]
 [179.8593 ]
 [197.5301 ]
 [141.58257]]
1250 Cost:  1.3615996 
Prediction:
 [[149.99135]
 [185.48682]
 [179.85999]
 [197.53012]
 [141.58113]]
1260 Cost:  1.3598865 
Prediction:
 [[149.99342]
 [185.48543]
 [179.8607 ]
 [197.53017]
 [141.57973]]
1270 Cost:  1.3581756 
Prediction:
 [[149.9955 ]
 [185.48405]
 [179.86137]
 [197.5