In [6]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost / loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph is a session
sess = tf.Session()
# Initializes gLobal variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1:x1_data, x2:x2_data,x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  226799.3 
Prediction:
 [-271.93893 -322.788   -320.20386 -347.76337 -245.99629]
10 Cost:  2.8254244 
Prediction:
 [149.34604 183.56364 178.71388 195.54507 140.22252]
20 Cost:  0.7487647 
Prediction:
 [150.6215  185.09518 180.22372 197.1888  141.39072]
30 Cost:  0.7483281 
Prediction:
 [150.62616 185.0993  180.22858 197.19362 141.39389]
40 Cost:  0.7479313 
Prediction:
 [150.62695 185.09882 180.22888 197.1935  141.39352]
50 Cost:  0.74752426 
Prediction:
 [150.62775 185.09831 180.22916 197.19336 141.39316]
60 Cost:  0.7471064 
Prediction:
 [150.62854 185.09782 180.22946 197.1932  141.39282]
70 Cost:  0.74669516 
Prediction:
 [150.62932 185.09729 180.22972 197.19304 141.39244]
80 Cost:  0.7463034 
Prediction:
 [150.6301  185.0968  180.23001 197.19292 141.39209]
90 Cost:  0.7458974 
Prediction:
 [150.63087 185.09631 180.2303  197.19276 141.39174]
100 Cost:  0.7454872 
Prediction:
 [150.63165 185.0958  180.23059 197.1926  141.39137]
110 Cost:  0.7450904 
Prediction:
 [150.63245 18

1250 Cost:  0.70394784 
Prediction:
 [150.71095 185.0455  180.26003 197.17381 141.35924]
1260 Cost:  0.7035985 
Prediction:
 [150.7116  185.04512 180.26028 197.17363 141.35905]
1270 Cost:  0.7032872 
Prediction:
 [150.71219 185.04474 180.2605  197.17346 141.35883]
1280 Cost:  0.7029594 
Prediction:
 [150.71278 185.04436 180.26073 197.17326 141.35861]
1290 Cost:  0.70263463 
Prediction:
 [150.7134  185.04398 180.26096 197.1731  141.35841]
1300 Cost:  0.7023066 
Prediction:
 [150.714   185.0436  180.26118 197.17291 141.3582 ]
1310 Cost:  0.701989 
Prediction:
 [150.71461 185.04323 180.26144 197.17276 141.35802]
1320 Cost:  0.7016717 
Prediction:
 [150.71521 185.04285 180.26166 197.17258 141.35779]
1330 Cost:  0.7013414 
Prediction:
 [150.7158  185.04247 180.26189 197.17238 141.35759]
1340 Cost:  0.70101917 
Prediction:
 [150.7164  185.04208 180.26208 197.1722  141.35738]
1350 Cost:  0.7006928 
Prediction:
 [150.717   185.04172 180.26231 197.17201 141.3572 ]
1360 Cost:  0.7003814 
Predict

In [7]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',',dtype=np.float32)
x_data = xy[:, 0:-1] # 0 to the (last element -1)
y_data = xy[:, [-1]] # y data is only one so [-1]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3]) # number of x's data is 3
Y = tf.placeholder(tf.float32, shape=[None, 1]) # number of y's data is 1

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost / Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the Loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110],[90, 100, 80]]}))


0 Cost:  104407.086 
Prediction:
 [[-141.09238]
 [-155.97844]
 [-160.83975]
 [-174.02022]
 [-116.41691]]
10 Cost:  15.924826 
Prediction:
 [[144.74007]
 [187.54259]
 [177.65208]
 [194.58696]
 [145.59769]]
20 Cost:  14.890503 
Prediction:
 [[145.61977]
 [188.57175]
 [178.68082]
 [195.70529]
 [146.37729]]
30 Cost:  14.8122 
Prediction:
 [[145.63727]
 [188.5647 ]
 [178.6885 ]
 [195.71173]
 [146.36652]]
40 Cost:  14.734247 
Prediction:
 [[145.65216]
 [188.55455]
 [178.6931 ]
 [195.71483]
 [146.3534 ]]
50 Cost:  14.656804 
Prediction:
 [[145.66698]
 [188.54442]
 [178.6977 ]
 [195.7179 ]
 [146.34032]]
60 Cost:  14.579755 
Prediction:
 [[145.68175]
 [188.53432]
 [178.70224]
 [195.72095]
 [146.32724]]
70 Cost:  14.503103 
Prediction:
 [[145.6965 ]
 [188.52423]
 [178.70679]
 [195.724  ]
 [146.31424]]
80 Cost:  14.42687 
Prediction:
 [[145.71121]
 [188.51419]
 [178.71133]
 [195.72702]
 [146.30125]]
90 Cost:  14.351064 
Prediction:
 [[145.72586]
 [188.50415]
 [178.71585]
 [195.73006]
 [146.2883 ]

840 Cost:  9.689755 
Prediction:
 [[146.72035]
 [187.82426]
 [179.0229 ]
 [195.93388]
 [145.41153]]
850 Cost:  9.639487 
Prediction:
 [[146.73228]
 [187.81609]
 [179.0266 ]
 [195.93631]
 [145.40099]]
860 Cost:  9.589496 
Prediction:
 [[146.74422]
 [187.80794]
 [179.03029]
 [195.93874]
 [145.39052]]
870 Cost:  9.539812 
Prediction:
 [[146.75609]
 [187.79982]
 [179.03395]
 [195.94116]
 [145.38005]]
880 Cost:  9.490335 
Prediction:
 [[146.76794]
 [187.7917 ]
 [179.03761]
 [195.94356]
 [145.36961]]
890 Cost:  9.441137 
Prediction:
 [[146.77979]
 [187.78363]
 [179.04128]
 [195.94597]
 [145.35922]]
900 Cost:  9.392243 
Prediction:
 [[146.79156]
 [187.77557]
 [179.04492]
 [195.94836]
 [145.34885]]
910 Cost:  9.343592 
Prediction:
 [[146.80331]
 [187.76752]
 [179.04855]
 [195.95074]
 [145.3385 ]]
920 Cost:  9.295179 
Prediction:
 [[146.81506]
 [187.75952]
 [179.05219]
 [195.95312]
 [145.32819]]
930 Cost:  9.247061 
Prediction:
 [[146.82675]
 [187.75151]
 [179.05579]
 [195.95549]
 [145.3179 ]]


1710 Cost:  6.192064 
Prediction:
 [[147.64886]
 [187.1898 ]
 [179.31007]
 [196.12079]
 [144.59656]]
1720 Cost:  6.1606445 
Prediction:
 [[147.65833]
 [187.18335]
 [179.31302]
 [196.12268]
 [144.58826]]
1730 Cost:  6.1294055 
Prediction:
 [[147.66777]
 [187.1769 ]
 [179.31593]
 [196.12453]
 [144.58002]]
1740 Cost:  6.0983286 
Prediction:
 [[147.67719]
 [187.17047]
 [179.31886]
 [196.12642]
 [144.57178]]
1750 Cost:  6.0674233 
Prediction:
 [[147.68657]
 [187.16406]
 [179.32176]
 [196.12828]
 [144.56355]]
1760 Cost:  6.0367317 
Prediction:
 [[147.69592]
 [187.15768]
 [179.32465]
 [196.13014]
 [144.55537]]
1770 Cost:  6.006118 
Prediction:
 [[147.70526]
 [187.15128]
 [179.32755]
 [196.13199]
 [144.5472 ]]
1780 Cost:  5.97573 
Prediction:
 [[147.71457]
 [187.14493]
 [179.33041]
 [196.13383]
 [144.53905]]
1790 Cost:  5.945479 
Prediction:
 [[147.72386]
 [187.13858]
 [179.3333 ]
 [196.1357 ]
 [144.53093]]
1800 Cost:  5.915405 
Prediction:
 [[147.73312]
 [187.13226]
 [179.33617]
 [196.13753]
