In [4]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',',dtype=np.float32)
x_data = xy[:, 0:-1] # 0 to the (last element -1)
y_data = xy[:, [-1]] # y data is only one so [-1]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3]) # number of x's data is 3
Y = tf.placeholder(tf.float32, shape=[None, 1]) # number of y's data is 1

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost / Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the Loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110],[90, 100, 80]]}))


(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  96164.51 
Prediction:
 [[-135.32027]
 [-167.32693]
 [-162.56483]
 [-177.32088]
 [-128.26009]
 [ -94.95628]
 [-131.37988]
 [ -95.50435]
 [-157.50093]
 [-146.51845]
 [-127.68465]
 [-127.88556]
 [-167.92047]
 [-139.44229]
 [-132.66574]
 [-169.55588]
 [-133.91872]
 [-157.0151 ]
 [-159.32127]
 [-141.96175]
 [-154.87697]
 [-

 [[155.94902]
 [183.2059 ]
 [182.57625]
 [198.69415]
 [139.08362]
 [102.39914]
 [150.14667]
 [113.28137]
 [170.36127]
 [157.49002]
 [143.55322]
 [139.81093]
 [188.53278]
 [156.71913]
 [150.23708]
 [186.2346 ]
 [148.11893]
 [180.82132]
 [180.4153 ]
 [161.99597]
 [175.27649]
 [172.18723]
 [167.5174 ]
 [157.13808]
 [190.45236]]
220 Cost:  14.426641 
Prediction:
 [[155.93631 ]
 [183.21118 ]
 [182.57037 ]
 [198.69368 ]
 [139.08788 ]
 [102.41381 ]
 [150.14932 ]
 [113.286964]
 [170.3782  ]
 [157.52061 ]
 [143.55585 ]
 [139.82484 ]
 [188.52101 ]
 [156.70229 ]
 [150.24347 ]
 [186.2437  ]
 [148.10208 ]
 [180.82349 ]
 [180.39998 ]
 [161.98111 ]
 [175.28044 ]
 [172.19664 ]
 [167.51776 ]
 [157.11191 ]
 [190.45183 ]]
230 Cost:  14.355313 
Prediction:
 [[155.92369]
 [183.21648]
 [182.56456]
 [198.69324]
 [139.09215]
 [102.42843]
 [150.15201]
 [113.29254]
 [170.3951 ]
 [157.5511 ]
 [143.55849]
 [139.83873]
 [188.50935]
 [156.68553]
 [150.24986]
 [186.2528 ]
 [148.08534]
 [180.82567]
 [180.38477]
 [161

610 Cost:  12.065266 
Prediction:
 [[155.48239 ]
 [183.40106 ]
 [182.3612  ]
 [198.67714 ]
 [139.24106 ]
 [102.93834 ]
 [150.24448 ]
 [113.486176]
 [170.98425 ]
 [158.61447 ]
 [143.64983 ]
 [140.32295 ]
 [188.10178 ]
 [156.10124 ]
 [150.47229 ]
 [186.56973 ]
 [147.50143 ]
 [180.90076 ]
 [179.85342 ]
 [161.45074 ]
 [175.42258 ]
 [172.53378 ]
 [167.5307  ]
 [156.17783 ]
 [190.43382 ]]
620 Cost:  12.01485 
Prediction:
 [[155.47173]
 [183.40552]
 [182.35631]
 [198.67674]
 [139.24464]
 [102.95063]
 [150.24669]
 [113.49081]
 [170.99843]
 [158.64009]
 [143.65202]
 [140.33461]
 [188.09193]
 [156.08714]
 [150.47762]
 [186.57735]
 [147.48738]
 [180.90254]
 [179.8406 ]
 [161.43831]
 [175.42587]
 [172.54167]
 [167.53099]
 [156.15594]
 [190.4334 ]]
630 Cost:  11.964844 
Prediction:
 [[155.46117]
 [183.40999]
 [182.35143]
 [198.67636]
 [139.24825]
 [102.96287]
 [150.24892]
 [113.49544]
 [171.01262]
 [158.66563]
 [143.65422]
 [140.34627]
 [188.08217]
 [156.07315]
 [150.48296]
 [186.58498]
 [147.4734 

1030 Cost:  10.289619 
Prediction:
 [[155.07347]
 [183.57257]
 [182.17303]
 [198.66206]
 [139.37979]
 [103.41071]
 [150.32925]
 [113.66378]
 [171.53012]
 [159.59882]
 [143.73416]
 [140.77135]
 [187.7248 ]
 [155.56102]
 [150.67746]
 [186.86339]
 [146.9622 ]
 [180.96889]
 [179.36176]
 [160.97343]
 [175.54973]
 [172.83743]
 [167.54163]
 [155.33743]
 [190.41818]]
1040 Cost:  10.254901 
Prediction:
 [[155.06462 ]
 [183.57628 ]
 [182.16896 ]
 [198.66174 ]
 [139.38281 ]
 [103.420944]
 [150.33109 ]
 [113.6676  ]
 [171.54193 ]
 [159.6201  ]
 [143.73598 ]
 [140.78104 ]
 [187.71666 ]
 [155.54935 ]
 [150.6819  ]
 [186.86974 ]
 [146.95058 ]
 [180.97034 ]
 [179.35115 ]
 [160.96312 ]
 [175.55247 ]
 [172.844   ]
 [167.54185 ]
 [155.31927 ]
 [190.41785 ]]
1050 Cost:  10.220478 
Prediction:
 [[155.05583 ]
 [183.57999 ]
 [182.16492 ]
 [198.6614  ]
 [139.3858  ]
 [103.431114]
 [150.3329  ]
 [113.6714  ]
 [171.55368 ]
 [159.6413  ]
 [143.7378  ]
 [140.79068 ]
 [187.70856 ]
 [155.53775 ]
 [150.6863  ]
 [186

1420 Cost:  9.140099 
Prediction:
 [[154.75592 ]
 [183.70612 ]
 [182.02711 ]
 [198.65024 ]
 [139.48819 ]
 [103.77746 ]
 [150.39432 ]
 [113.800186]
 [171.95398 ]
 [160.36238 ]
 [143.79936 ]
 [141.11928 ]
 [187.43268 ]
 [155.14258 ]
 [150.83603 ]
 [187.09143 ]
 [146.54501 ]
 [181.02057 ]
 [178.98053 ]
 [160.60321 ]
 [175.64777 ]
 [173.07317 ]
 [167.5495  ]
 [154.68573 ]
 [190.40654 ]]
1430 Cost:  9.115564 
Prediction:
 [[154.74849]
 [183.70924]
 [182.0237 ]
 [198.64995]
 [139.49074]
 [103.78606]
 [150.39583]
 [113.80336]
 [171.96391]
 [160.38026]
 [143.80089]
 [141.12743]
 [187.42583]
 [155.13277]
 [150.83972]
 [187.09676]
 [146.53525]
 [181.02176]
 [178.9716 ]
 [160.59453]
 [175.65005]
 [173.07869]
 [167.54967]
 [154.67047]
 [190.40627]]
1440 Cost:  9.09124 
Prediction:
 [[154.74106]
 [183.71237]
 [182.0203 ]
 [198.64967]
 [139.49326]
 [103.79462]
 [150.39734]
 [113.80652]
 [171.9738 ]
 [160.39809]
 [143.8024 ]
 [141.13554]
 [187.41904]
 [155.12302]
 [150.84341]
 [187.10208]
 [146.52553

1840 Cost:  8.275662 
Prediction:
 [[154.46979 ]
 [183.82677 ]
 [181.89583 ]
 [198.63943 ]
 [139.58644 ]
 [104.107796]
 [150.45216 ]
 [113.92158 ]
 [172.33583 ]
 [161.04955 ]
 [143.85783 ]
 [141.43251 ]
 [187.17006 ]
 [154.76653 ]
 [150.97813 ]
 [187.29686 ]
 [146.1706  ]
 [181.06593 ]
 [178.63762 ]
 [160.26997 ]
 [175.73541 ]
 [173.2855  ]
 [167.55598 ]
 [154.09938 ]
 [190.39653 ]]
1850 Cost:  8.258758 
Prediction:
 [[154.4636 ]
 [183.82938]
 [181.89299]
 [198.63919]
 [139.58858]
 [104.11493]
 [150.4534 ]
 [113.92417]
 [172.34407]
 [161.06439]
 [143.8591 ]
 [141.43927]
 [187.1644 ]
 [154.75842]
 [150.98119]
 [187.3013 ]
 [146.16252]
 [181.0669 ]
 [178.63019]
 [160.26277]
 [175.73729]
 [173.2901 ]
 [167.55612]
 [154.08672]
 [190.39633]]
1860 Cost:  8.242012 
Prediction:
 [[154.45744]
 [183.83199]
 [181.89017]
 [198.63896]
 [139.5907 ]
 [104.12205]
 [150.45464]
 [113.92677]
 [172.3523 ]
 [161.07918]
 [143.86035]
 [141.446  ]
 [187.15874]
 [154.75032]
 [150.98424]
 [187.30571]
 [146.1544