In [1]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost / loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph is a session
sess = tf.Session()
# Initializes gLobal variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1:x1_data, x2:x2_data,x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  48665.242 
Prediction:
 [-49.734436 -47.258522 -53.566338 -53.431496 -36.65085 ]
10 Cost:  11.951993 
Prediction:
 [145.40074 187.26035 177.51912 198.2125  142.22514]
20 Cost:  11.470871 
Prediction:
 [146.00127 187.96312 178.22154 198.97514 142.75835]
30 Cost:  11.4353285 
Prediction:
 [146.01315 187.95844 178.2269  198.9787  142.75195]
40 Cost:  11.400006 
Prediction:
 [146.02322 187.95163 178.23012 198.97995 142.74396]
50 Cost:  11.364863 
Prediction:
 [146.03328 187.94487 178.23337 198.98122 142.73598]
60 Cost:  11.32981 
Prediction:
 [146.04332 187.9381  178.23657 198.98244 142.72801]
70 Cost:  11.295004 
Prediction:
 [146.0533  187.93134 178.23975 198.98363 142.72008]
80 Cost:  11.260356 
Prediction:
 [146.06331 187.92465 178.243   198.9849  142.7122 ]
90 Cost:  11.225924 
Prediction:
 [146.07324 187.91792 178.24615 198.98611 142.7043 ]
100 Cost:  11.191621 
Prediction:
 [146.08316 187.91122 178.24934 198.98732 142.69643]
110 Cost:  11.157545 
Prediction:
 [146.09306 187

1290 Cost:  8.121502 
Prediction:
 [147.09888 187.22781 178.577   199.09674 141.90724]
1300 Cost:  8.102569 
Prediction:
 [147.10614 187.2229  178.57935 199.09738 141.9017 ]
1310 Cost:  8.083671 
Prediction:
 [147.11345 187.21803 178.58173 199.09807 141.8962 ]
1320 Cost:  8.064894 
Prediction:
 [147.12071 187.2132  178.5841  199.09872 141.89073]
1330 Cost:  8.046214 
Prediction:
 [147.12793 187.20833 178.58644 199.09935 141.88524]
1340 Cost:  8.027643 
Prediction:
 [147.13515 187.20349 178.5888  199.10002 141.87979]
1350 Cost:  8.0091 
Prediction:
 [147.14236 187.19867 178.59113 199.10065 141.87433]
1360 Cost:  7.9907 
Prediction:
 [147.14954 187.19385 178.59346 199.10129 141.8689 ]
1370 Cost:  7.9723206 
Prediction:
 [147.1567  187.18901 178.5958  199.1019  141.86346]
1380 Cost:  7.9540987 
Prediction:
 [147.16383 187.18425 178.59813 199.10252 141.85808]
1390 Cost:  7.935923 
Prediction:
 [147.17097 187.17947 178.60046 199.10316 141.85272]
1400 Cost:  7.91784 
Prediction:
 [147.17809 